bindd = $mainMod, K, Toggles  current window group mode (ungroup all related), togglegroup,
bindd = $mainMod, Tab, Switches to the next window in the group, changegroupactive, f


# TODO: IS THIS LOGOUT ?? ADD ONE FOR POWEROFF!
# TODO: SHOULD I EXIT LIKE THIS?? OR IS THERE A BETTER WAY
bind = $mainMod, M, exit
# TODO: LIKE THIS PROBABLY??
bindd = $mainMod SHIFT, M, Exits Hyprland by terminating the user sessions, exec, loginctl terminate-user ""

#bindd = $mainMod, L, Lock the screen, exec, swaylock-fancy -e -K -p 10 -f Hack-Regular

