# Defaults
$mainMod = SUPER
$terminal = ghostty
$fileManager = thunar
$menu = wofi --show drun

# Base Config
source = ~/.config/colors/hypr-colors.conf
source = ~/.config/hypr/config/environment.conf
source = ~/.config/hypr/config/hypr-core-legacy.conf
source = ~/.config/hypr/config/autostart.conf

# Eye Candy
source = ~/.config/hypr/config/decorations.conf
source = ~/.config/hypr/config/animations.conf

# Input
source = ~/.config/hypr/config/mouse.conf
source = ~/.config/hypr/config/keyboard.conf
source = ~/.config/hypr/config/keybinds.conf

# Window and layer management.
source = ~/.config/hypr/config/windowrules.conf

# Workspaces (Keybinds & rules)
source = ~/.config/hypr/config/workspaces.conf

# App Configuration
source = ~/.config/hypr/config/apps/*

# Config / Feature that are either unstable, OR I am not sure I want / need them.
source = ~/.config/hypr/experimental.conf

# User / Machine specific Configuration
source = ~/.config/hypr/config/user-config.conf

# General Settings
general {
    allow_tearing = true
    layout = dwindle
    resize_on_border = true
}

misc {
    font_family = "JetBrainsMono Nerd Font Propo"
    disable_hyprland_logo = true
    enable_swallow = true
    swallow_regex = ^(com.mitchellh.ghostty)$
}

render {
   direct_scanout = 1
}


# TODO: Move to hyprshot in apps or screencapture generic?
env = HYPRSHOT_DIR,$HOME/Pictures/Screenshots/

# TODO: Move to other file (Maybe keybinds) (Or screencapture). 
# Screenshot a monitor
bind = , PRINT, exec, hyprshot -m output  -r - | swappy -f -
# Screenshot a window
bind = $mainMod, PRINT, exec, hyprshot -m window  -r - | swappy -f -
# Screenshot a region
bind = $shiftMod, PRINT, exec, hyprshot -m region -r - | swappy -f -

# TODO: Move somewhere else.
# TODO: - Probably a generic laptop config?
# TODO: - Fix HDR
# TODO: - Will need handling afer idle inhibitor setup
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, preferred, auto, 1.5"


# HP Inc. OMEN 27q CNC3361KCJ - 165Hz - Right
# TODO: How to set this up for the specific screen using monitorv2 (ask in repo).
# TODO: Move these to laptop config or a general monitors config if per monitor?
#monitor = desc:HP Inc. OMEN 27q CNC3361KCJ,2560x1440@165,auto,auto
monitorv2 {
  output = DP-4
  mode = 2560x1440@165
  position = 0x0
  scale = 1
	#  bitdepth = 10
	#  cm = hdr
	#  supports_wide_color = 1
	#  supports_hdr = 1
	#  sdrbrightness = 1.2
	#  sdrsaturation = 1.0
}

#TODO: Try to add bezier to the animation (Ask discord?)
layerrule {
  name = korompos
  match:namespace = swaync-control-center
  animation = slide right
}
