# Config / Feature that are either unstable, OR I am not sure I want / need them.
source = ~/.config/hypr/experimental.conf

# User / Machine specific Configuration
source = ~/.config/hypr/config/user-config.conf



# TODO: Move to hyprshot in apps or screencapture generic?
env = HYPRSHOT_DIR,$HOME/Pictures/Screenshots/

# TODO: Move to other file (Maybe keybinds) (Or screencapture). 
# Screenshot a monitor
bind = , PRINT, exec, hyprshot -m output  -r - | swappy -f -
# Screenshot a window
bind = $mainMod, PRINT, exec, hyprshot -m window  -r - | swappy -f -
# Screenshot a region
bind = $shiftMod, PRINT, exec, hyprshot -m region -r - | swappy -f -

# TODO: Move somewhere else.
# TODO: - Probably a generic laptop config?
# TODO: - Fix HDR
# TODO: - Will need handling afer idle inhibitor setup
# TODO: - Lid open is buggy
#bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
#bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, preferred, auto, 1.5"


