# Defaults
$mainMod = SUPER
$terminal = ghostty
$fileManager = thunar
$menu = wofi --show drun

# Base Config
source = ~/.config/colors/hypr-colors.conf
source = ~/.config/hypr/config/environment.conf
source = ~/.config/hypr/config/hypr-core-legacy.conf

# Eye Candy
source = ~/.config/hypr/config/decorations.conf
source = ~/.config/hypr/config/animations.conf

# Input
source = ~/.config/hypr/config/mouse.conf
source = ~/.config/hypr/config/keyboard.conf
source = ~/.config/hypr/config/keybinds.conf

# Window and layer management.
source = ~/.config/hypr/config/windowrules.conf

# App Configuration
source = ~/.config/hypr/config/apps/jetbrains.conf
source = ~/.config/hypr/config/apps/waybar.conf

# Config / Feature that are either unstable, OR I am not sure I want / need them.
source = ~/.config/hypr/experimental.conf

# User / Machine specific Configuration
source = ~/.config/hypr/config/user-config.conf

# General Settings
general {
    gaps_in = 2
    gaps_out = 4
    border_size = 2
    col.active_border = $blue
    allow_tearing = true
    layout = dwindle
    resize_on_border = true
}

misc {
    font_family = "JetBrainsMono Nerd Font Propo"
    disable_hyprland_logo = true
    enable_swallow = true
    swallow_regex = ^(com.mitchellh.ghostty)$
}

render {
   direct_scanout = 1
}


#source = ~/.config/hypr/config/autostart.conf



# Register clipboard manager.
exec-once = wl-paste --watch cliphist store &
# Autostart bluetooth device manager.
exec-once = blueman-applet --no-tray &

# TODO: Move to some other file.
exec-once = hyprpaper

# TODO: Move to some other file.
windowrule = opacity 0.92, match:class com.mitchellh.ghostty


# TODO: Move to hyprshot in apps or screencapture generic?
env = HYPRSHOT_DIR,$HOME/Pictures/Screenshots/

# TODO: Move to other file (Maybe keybinds) (Or screencapture). 
# Screenshot a monitor
bind = , PRINT, exec, hyprshot -m output  -r - | swappy -f -
# Screenshot a window
bind = $mainMod, PRINT, exec, hyprshot -m window  -r - | swappy -f -
# Screenshot a region
bind = $shiftMod, PRINT, exec, hyprshot -m region -r - | swappy -f -




# TODO: Move somewhere else.
# TODO: - Probably a generic laptop config?
# TODO: - Will need handling afer idle inhibitor setup
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, preferred, auto, 1.5"
