decoration {
    rounding = 8
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

    blur {
        enabled = true
        size = 5
        passes = 3
        vibrancy = 0.1696
        xray = true
    }

    shadow {
        enabled = false
    }
}
