input {
    # Follow mouse but do not change keyboard focus
    follow_mouse = 2
    # -1.0 - 1.0, 0 means no modification.
    sensitivity = 0
    float_switch_override_focus = 2

    touchpad {
        disable_while_typing = true
        natural_scroll = false
	# Map click+drag to a three finger drag.
	drag_3fg = true
    }
}
# Cycle through workspace on 4 finger drag.
gesture = 4, horizontal, workspace
