# Float Necessary Windows.
## By title.
windowrule = float on, match:title ^(Picture in picture)$
windowrule = float on, match:title ^(Save File)$
windowrule = float on, match:title ^(.*wants to save)$
windowrule = float on, match:title ^(Open File)$

#TODO: FIX.. see https://github.com/hyprwm/Hyprland/issues/12412
#windowrule = float on, match:title ^(btop)$

#windowrule {
#    name = btop-popup
#    match:title = ^(btop)$
#    min_size = 180 124
#    float = on
#}

#windowrule = float on, min_size 200 200, match:title ^(btop)$

## By app.
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on, match:class ^(thunar)$
windowrule = float on, match:class ^(org.kde.kcalc)$
windowrule = float on, match:class ^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$
windowrule = float on, match:class ^(org.cachyos.hello)$
windowrule = float on, match:class ^()$, match:title ^(Steam - Self Updater)$
# Opacity Rules.
## By app.
windowrule = opacity 0.92, match:class com.mitchellh.ghostty

