# Float Necessary Windows.
## By title.
windowrule = float on, match:title ^(Picture in picture)$
windowrule = float on, match:title ^(Save File)$
windowrule = float on, match:title ^(Open File)$
windowrule = float on, match:title ^(btop)$
## By app.
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on, match:class ^(thunar)$
windowrule = float on, match:class ^(org.kde.kcalc)$
windowrule = float on, match:class ^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$
windowrule = float on, match:class ^(org.cachyos.hello)$
windowrule = float on, match:class ^()$, match:title ^(Steam - Self Updater)$
# Opacity Rules.
## By app.
windowrule = opacity 0.92, match:class com.mitchellh.ghostty

