# Float Necessary Windows
# By title for generic operations.
windowrule = float on, match:class ^()$, match:title ^(Picture in picture)$
windowrule = float on, match:class ^()$, match:title ^(Save File)$
windowrule = float on, match:class ^()$, match:title ^(Open File)$
# By app.
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(thunar)$
windowrule = float on, match:class ^(org.kde.kcalc)$
windowrule = float on, match:class ^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$
windowrule = float on, match:class ^(CachyOSHello)$

windowrule = float on, match:class ^()$, match:title ^(Steam - Self Updater)$
