
# Waybar Initialization.
# Initialize top and bottom bars separatly to be able to toggle them separatly
exec-once = waybar -c $XDG_CONFIG_HOME/waybar/top.jsonc &
exec-once = waybar -c $XDG_CONFIG_HOME/waybar/bottom.jsonc &
# Waybar toggle submap
bindd = $mainMod, W, Waybar toggle mode, submap, waybar
submap = waybar
# Toggle top bar.
bindd = , T, Toggle top bar, exec, pkill -SIGUSR1 -f "waybar -c .*top.jsonc"
# Toggle bottom bar.
bindd = , B, Toggle bottom bar, exec, pkill -SIGUSR1 -f "waybar -c .*bottom.jsonc"
bindd = , escape, Exit submap, submap, reset
submap = reset
